from a_rchive.b_prac_ps.core.models import User



def main():
    run_email_sim()
    # pass


def run_email_sim(): 
    # generated by ai tutor 
    print("=== Welcome to the Odoo Mail ===")
    
    # 1. SETUP PHASE: Instantiate our data records
    alice = User(name="Alice")
    bob = User(name="Bob")
    
    # Store users in a dictionary for quick terminal lookup
    system_users = {"1": alice, "2": bob}
    
    # 2. INTERFACE PHASE: Main application execution loop
    while True:
        print("\n--- Current Active Session Profiles ---")
        print(f"1. Open Alice's Terminal")
        print(f"2. Open Bob's Terminal")
        print( "3. Exit Simulation")
        
        user_choice = input("\nSelect a profile menu option (1-3): ").strip()
        
        if user_choice == "3":
            print("\nShutting down sandbox mail engine. Goodbye!")
            break
            
        if user_choice in system_users:
            current_user = system_users[user_choice]
            # Find out who the other person is to handle routing target
            receiver_user = bob if current_user == alice else alice
            
            # Sub-Menu for the chosen user profile
            while True:
                print(f"\n=============================")
                print(f"👤 PROFILE VIEW: {current_user.name.upper()}")
                print(f"=============================")
                print("1. Check Inbox Directory")
                print("2. Send an Email")
                print("3. Read a Specific Email")
                print("4. Log out of profile")
                
                action = input("Select an action (1-4): ").strip()
                
                if action == "4":
                    break  # Breaks out of sub-menu, goes back to main profiles

                elif action == "1":
                    # ODOO PATTERN CHECK: We print the string returned by our accessor
                    inbox_view = current_user.check_inbox()
                    print(inbox_view)

                elif action == "2":
                    print(f"\nWriting email to {receiver_user.name}...")
                    subject = input("Enter Subject line: ")
                    body = input("Enter Message Body: ")
                    
                    # Triggers the backend model composition chain reaction method
                    current_user.send_email(receiver_user, subject, body)
                    print(f"✔️ Success: Email dispatched to {receiver_user.name}!")

                elif action == "3": 
                    # Check if the inbox has emails before bothering to ask for a number
                    if not current_user.inbox.emails:
                        print("\n Your inbox is empty. Nothing to read!")
                        continue
                
                    try:
                        choice_num = int(input("Enter the email number you want to read: "))
                        # Array index starts at 0, but directory lists starting at 1
                        actual_index = choice_num - 1 
                    
                        # Fetch and print the formatted email content from our model
                        email_content = current_user.inbox.get_and_read_email(actual_index)
                        print(email_content)
                    except ValueError:
                        print("⚠️ Please enter a valid numerical number.")

        else:
            print("⚠️ Invalid Selection. Please pick 1, 2, 3, or 4.")



# ============================================================================

# instance = obj -> implementation of ds/class on data to create  obj

# pet_1=dog("max","GR",5)

# print(pet_1.bark())

# print(f"{pet_1.eat("fish")}")



if __name__ == '__main__':
    main()